### ISSUE TITLE
Item stops saving when group layout added

### ISSUE THREAD

**Issue by ThisMushroom** [ptkio/directus-extension-group-layout-sidebar#2] opened 2024-05-16 07:57 UTC
Directus 10.10.5

On item creation - everything works great.

Whenever I try to update item - changes doesn't save.

No errors in directus. But payload to save remains the same as it was before save.

If I try to delete layout groups - still they remain broken and doesn't save. 

Therefore, at the moment one adds group layout - collection can be considered as broken. 
Only recreation of the collection fix things.

**Comment by ThisMushroom** [comment] 2024-05-16 08:02
After digging little bit further - problem appears when there are non blocking flow for the collection

**Comment by ptkio** [comment] 2024-05-31 09:13
Hello, Thank you for your feedback.
I have a lot of non-blocking flows and I can't reproduce the issue.
Whether it's for editing the collection or saving an item, everything works fine on my end.
Are you still experiencing the issue? Do you have more details?
Can you give me the list of installed extensions?

**Comment by ptkio** [comment] 2024-06-23 20:01
Hi,

As I have not received any further feedback, I will be closing this issue for now. If you still encounter problems or have additional questions, please feel free to reopen this issue or create a new one.

Thank you for your understanding.

**Closed as completed by ptkio** 2024-06-23 20:01 UTC
